### ISSUE TITLE
"Edit Model Masks" not working properly

### ISSUE THREAD

**Issue by Smujb** [AmirBohd/SoulsOutfitManager#1]
![image](https://user-images.githubusercontent.com/15002583/124154005-f70c7f00-da8c-11eb-9d45-79028ee1b324.png)

For some users, myself included, this is displayed when clicking on an item in the edited models, instead of a series of checklists.

The buttons seem to not be loading at all, as pressing "update model/mask changes" generates a completely empty .json file _which will cause the tool to crash when opened until deleted._

This is definitely user/system specific however, as other users have it working fine.

**Comment by AmySouls** [comment]
I'll take a look at this soon, I'll need to send out some users a debug version to log exactly what's happening.

**Comment by Smujb** [comment]
I think I have found the source of the issue. This part of the program started working for me once I tried it when the game was already running. It is likely something to do with whether the game is launched.

**Comment by Smujb** [comment]
Ok, some more info

It seems the params reset when restarting the game

Does the manager only change them per-session?

**Comment by AmySouls** [comment]
Only when you launch the game or click Save & Update Presets

**Comment by AmySouls** [comment]
I've updated it to refresh the game params when you relaunch the game, and to patch the model masks if you edited them on a 3 second tick. Closed by c892a9a
